import { groupKlineSignals } from "./kline-signal-groups.ts";

export function signalLayoutBootstrap() {
  return `<style id="hanstock-candle-signal-style">
[data-hanstock-condensed-source="true"],[data-hanstock-condensed-native="true"]>line{visibility:hidden!important}
html[data-hanstock-five-minute-signals="hidden"] #hanstock-candle-signals,
html[data-hanstock-five-minute-signals="hidden"] #hanstock-candle-signal-details,
html[data-hanstock-five-minute-signals="hidden"] #hanstock-candle-signal-hover{display:none!important}
#hanstock-five-minute-signal-controls{flex-wrap:wrap}
#hanstock-candle-signal-details{flex:1 0 100%;padding:10px;border:1px solid #7a6a3d;border-radius:7px;background:#131a23;color:#fff;white-space:pre-line;text-align:left;font:600 13px/1.7 system-ui}
#hanstock-candle-signal-details button{float:right;cursor:pointer;color:#fff;background:#334155;border:1px solid #64748b;border-radius:4px}
#hanstock-candle-signals>g{cursor:pointer;pointer-events:all}#hanstock-candle-signals>g:focus{outline:2px solid #facc15}
#hanstock-candle-signal-hover{position:fixed;z-index:10050;max-width:min(360px,calc(100vw - 24px));box-sizing:border-box;padding:10px 14px;border:1px solid #d9bc68;border-radius:8px;background:#131a23;color:#fff;box-shadow:0 6px 24px #0009;white-space:pre-line;overflow-wrap:anywhere;pointer-events:none;font:600 14px/1.6 system-ui}
#hanstock-candle-signal-hover[hidden]{display:none!important}
</style><script id="hanstock-signal-collision-layout">
(()=>{
const groupSignals=${groupKlineSignals.toString()},ns="http://www.w3.org/2000/svg",loc=n=>'[data-loc="client/src/components/CandleChartDialog.tsx:'+n+'"]',upKinds=new Set(["crossUp905","firstCross905High","crossUpPrevHigh","crossUp20ma","firstCrossUp20ma","ma520Up","fiveMinuteOnePlusTwoLong"]),states=new WeakMap();
let queued=false;
let hoverTip=null;
const hideHover=()=>{if(hoverTip)hoverTip.hidden=true};
const hover=(group,g,event)=>{if(event?.pointerType==='touch'||event?.buttons)return;const rect=g.getBoundingClientRect();if(!hoverTip){hoverTip=document.createElement('div');hoverTip.id='hanstock-candle-signal-hover';hoverTip.setAttribute('role','tooltip');document.body.appendChild(hoverTip)}const text=group.date+' · '+group.items.length+' 個訊號\\n'+group.items.map(item=>item.label).join('\\n');if(hoverTip.textContent!==text)hoverTip.textContent=text;hoverTip.hidden=false;const x=Number.isFinite(event?.clientX)?event.clientX:rect.left+rect.width/2,y=Number.isFinite(event?.clientY)?event.clientY:rect.bottom,w=hoverTip.offsetWidth,h=hoverTip.offsetHeight;hoverTip.style.left=Math.max(12,Math.min(window.innerWidth-w-12,x+14))+'px';hoverTip.style.top=Math.max(12,y+16+h<=window.innerHeight-12?y+16:y-h-16)+'px'};
const point=(svg,matrix,x,y)=>{const p=svg.createSVGPoint();p.x=x;p.y=y;return p.matrixTransform(matrix)},convert=(svg,from,to,x,y)=>{const p=point(svg,from.getCTM(),x,y);return point(svg,to.getCTM().inverse(),p.x,p.y)},el=(name,attrs={})=>{const node=document.createElementNS(ns,name);for(const [key,value]of Object.entries(attrs))node.setAttribute(key,String(value));return node};
const details=group=>{const host=document.getElementById('hanstock-five-minute-signal-controls');if(!host)return;let panel=document.getElementById('hanstock-candle-signal-details');if(!panel){panel=document.createElement('div');panel.id='hanstock-candle-signal-details';host.appendChild(panel)}panel.hidden=false;panel.textContent=group.date+' · '+group.items.length+' 個訊號\\n'+group.items.map(item=>item.label).join('\\n');const close=document.createElement('button');close.type='button';close.textContent='關閉';close.onclick=()=>{panel.hidden=true};panel.prepend(close)};
const render=()=>{queued=false;const active=window.__hanstockActiveInterval||new URLSearchParams(location.search).get('interval')||'5m';if(active!=='5m'){hideHover();for(const node of document.querySelectorAll('#hanstock-candle-signals'))node.remove();return}if(window.__hanstockSignalMarkersVisible===false){hideHover();return}
for(const svg of document.querySelectorAll('svg')){const candles=[...svg.querySelectorAll(loc(2158))],layer=candles[0]?.parentElement;if(!layer||!svg.getBoundingClientRect().width)continue;
const nodes=[...svg.querySelectorAll('#hanstock-signal-overlay>g,'+loc(2305))].filter(node=>!node.closest('#hanstock-candle-signals')),byDate=new Map(candles.map(c=>[c.getAttribute('data-hanstock-bar-date'),c])),items=[];
for(const node of nodes){const native=node.closest(loc(2288));if(native?.style.display==='none')continue;const date=node.getAttribute('data-hanstock-signal-time')||native?.getAttribute('data-hanstock-native-signal-date'),candle=byDate.get(date),line=candle?.querySelector('line');if(!line)continue;
try{const box=node.getBBox(),parent=node.parentElement,a=convert(svg,line,layer,Number(line.getAttribute('x1')),Number(line.getAttribute('y1'))),b=convert(svg,line,layer,Number(line.getAttribute('x2')),Number(line.getAttribute('y2'))),kind=node.getAttribute('data-hanstock-signal-kind')||node.textContent,rawNote=node.getAttribute('data-hanstock-signal-note')||'',side=native?.getAttribute('data-hanstock-native-signal-side')||(upKinds.has(kind)||kind==='ma20turn'&&rawNote!=='down'?'up':'down'),anchorY=side==='up'?Math.min(a.y,b.y):Math.max(a.y,b.y),x=(a.x+b.x)/2,note=kind==='ma20turn'?side:rawNote,label=node.getAttribute('data-hanstock-signal-label')||node.querySelector('title')?.textContent||node.textContent;
if(![x,anchorY,box.width,box.height].every(Number.isFinite)||!box.width||!box.height)continue;items.push({node,parent,native,box,x,anchorY,date,id:String(items.length),kind,note,label,side,source:native?'native':'overlay'})}catch{}}
const separator=svg.querySelector(loc(2428));if(!items.length){svg.querySelector('#hanstock-candle-signals')?.remove();continue}if(!separator)continue;
try{const left=convert(svg,separator,layer,Number(separator.getAttribute('x1')),0).x,right=convert(svg,separator,layer,Number(separator.getAttribute('x2')),0).x,bottom=convert(svg,separator,layer,0,Number(separator.getAttribute('y1'))).y,bounds={left:Math.min(left,right),right:Math.max(left,right),top:10,bottom:bottom-6};if(bounds.right-bounds.left<40||bounds.bottom<60)continue;
const xs=candles.flatMap(c=>{const line=c.querySelector('line');return line?[convert(svg,line,layer,Number(line.getAttribute('x1')),0).x]:[]}).sort((a,b)=>a-b),steps=xs.slice(1).map((x,i)=>x-xs[i]).filter(x=>x>0),step=steps.length?Math.min(...steps):30,groups=groupSignals(items),matrix=layer.getCTM(),signature=JSON.stringify([bounds,step,matrix.a,matrix.d,matrix.e,matrix.f,items.map(i=>[i.date,i.kind,i.note,i.label,i.x,i.anchorY,i.side,i.box.width,i.box.height])]),previous=states.get(svg);
if(previous?.signature===signature&&previous.nodes.length===items.length&&items.every((i,n)=>previous.nodes[n]===i.node)&&svg.querySelector('#hanstock-candle-signals'))continue;
const output=el('g',{id:'hanstock-candle-signals','data-coordinate-space':'candle-layer'});let shown=0;
const slots=new Map(),sizes=new Map(),positions=new Map();
for(const group of groups){const square=group.items.length>1||!!items[Number(group.items[0].id)].node.querySelector('rect'),size=Math.max(6,Math.min(24,step*.82))*(square?1.3:1.5),key=group.date+'|'+group.side;sizes.set(group,{square,size});const slot=slots.get(key)||[];slot.push(group);slots.set(key,slot)}
// Separate the standalone break35 glyph from its same-candle count box, including hit areas.
for(const slot of slots.values()){const gap=8,sum=slot.reduce((n,g)=>n+sizes.get(g).size,0),scale=Math.min(1,Math.max(1,bounds.bottom-bounds.top-gap*(slot.length-1))/sum),height=sum*scale+gap*(slot.length-1),first=slot[0],top=Math.max(bounds.top,Math.min(bounds.bottom-height,first.anchorY+(first.side==='up'?-height-7:7)));let offset=0;for(const group of slot){const metric=sizes.get(group);metric.size*=scale;positions.set(group,first.side==='up'?top+height-offset-metric.size/2:top+offset+metric.size/2);offset+=metric.size+gap}}
for(const group of groups){if(group.x<bounds.left||group.x>bounds.right)continue;const {square,size}=sizes.get(group),y=positions.get(group),g=el('g',{'data-hanstock-signal-time':group.date,'data-signal-count':group.items.length,'data-marker-size':size,'data-marker-shape':square?'square':'round','data-anchor-x':group.x,tabindex:0,role:'button','aria-label':group.date+'，'+group.items.map(i=>i.label).join('；')});
g.appendChild(el('rect',{'data-signal-hit-area':'true',x:group.x-size/2-4,y:y-size/2-4,width:size+8,height:size+8,fill:'transparent','pointer-events':'all'}));
const title=el('title');title.textContent=group.date+' · '+group.items.length+' 個訊號\\n'+group.items.map(item=>item.label).join('\\n')+'\\n點選查看完整訊號';g.appendChild(title);
if(group.items.length===1){const item=items[Number(group.items[0].id)],clone=item.node.cloneNode(true),scale=size/Math.max(item.box.width,item.box.height);clone.removeAttribute('data-hanstock-condensed-source');clone.removeAttribute('data-loc');clone.removeAttribute('data-hanstock-packed-signal');clone.style.visibility='visible';clone.setAttribute('transform','translate('+group.x+' '+y+') scale('+scale+') translate('+(-(item.box.x+item.box.width/2))+' '+(-(item.box.y+item.box.height/2))+')');g.appendChild(clone)}else{const color=group.side==='up'?'#a73539':'#19613f';g.appendChild(el('rect',{x:group.x-size/2,y:y-size/2,width:size,height:size,rx:3,fill:color,stroke:'#e2e8f0','stroke-width':.8}));const text=el('text',{x:group.x,y,'text-anchor':'middle','dominant-baseline':'central','font-size':Math.max(5,size*.62),'font-weight':900,fill:'#fff'});text.textContent=String(group.items.length);g.appendChild(text)}
g.addEventListener('pointerenter',event=>hover(group,g,event));g.addEventListener('pointermove',event=>hover(group,g,event));g.addEventListener('pointerleave',hideHover);g.addEventListener('pointerdown',hideHover);g.addEventListener('focus',()=>hover(group,g));g.addEventListener('blur',hideHover);g.addEventListener('click',event=>{event.stopPropagation();hideHover();details(group)});g.addEventListener('keydown',event=>{if(event.key==='Escape'){hideHover();return}if(event.key==='Enter'||event.key===' '){event.preventDefault();event.stopPropagation();hideHover();details(group)}});output.appendChild(g);shown++}
hideHover();
svg.querySelector('#hanstock-candle-signals')?.remove();svg.querySelector('#hanstock-signal-leaders')?.remove();layer.appendChild(output);
for(const item of items){if(item.node.getAttribute('data-hanstock-condensed-source')!=='true')item.node.setAttribute('data-hanstock-condensed-source','true');if(item.native)item.native.setAttribute('data-hanstock-condensed-native','true')}
states.set(svg,{signature,nodes:items.map(i=>i.node)});window.__hanstockSignalLayoutCount=groups.reduce((n,g)=>n+g.items.length,0);window.__hanstockSignalVisibleGroupCount=shown;
}catch{}}
};
const queue=()=>{if(!queued){queued=true;requestAnimationFrame(render)}};
new MutationObserver(records=>{if(records.some(r=>!r.target.closest?.('#hanstock-candle-signals,#hanstock-candle-signal-details,#hanstock-candle-signal-hover')))queue()}).observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['x','y','x1','x2','y1','y2','cx','cy','r','width','height','transform','viewBox','style']});
for(const event of ['scroll','resize','blur','hanstock-period-change','hanstock-signal-session-change','hanstock-signal-visibility-change'])window.addEventListener(event,hideHover,{passive:true});
for(const event of ['resize','orientationchange','hanstock-candles-updated','hanstock-period-change','hanstock-signal-session-change','hanstock-signal-visibility-change'])window.addEventListener(event,queue,{passive:true});document.addEventListener('DOMContentLoaded',queue);queue();
})();
</script>`;
}
